package com.tweeks.translator.emit

import java.nio.file.Path
import java.util.TreeMap
import java.util.TreeSet
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Per-mod accumulator for translation losses.
 *
 * Phase 1a's transforms call into one of these as they encounter Bedrock-
 * incompatible inputs. After the pipeline runs for a mod, [writeFor]
 * regenerates `bedrock-out/<modid>/UNTRANSLATABLE.md` with the recorded
 * findings. Empty sections are omitted; if a mod has no losses at all, an
 * "everything translated cleanly" banner is emitted so reviewers know this
 * isn't a stale report.
 */
class Untranslatable {

    // Per-mod buckets — TreeMap/TreeSet for stable, sorted output.

    private val recipeCategoryDropped = TreeMap<String, TreeSet<String>>()
    private val recipeTypeSkipped = TreeMap<String, TreeMap<String, String>>()
    private val lootRandomSequenceDropped = TreeMap<String, TreeSet<String>>()
    private val soundSubtitleDropped = TreeMap<String, TreeSet<String>>()
    private val vanillaSoundPaths = TreeMap<String, TreeMap<String, String>>()

    fun recordRecipeCategoryDropped(modId: String, recipeName: String) {
        recipeCategoryDropped.getOrPut(modId) { TreeSet() }.add(recipeName)
    }

    fun recordRecipeTypeSkipped(modId: String, recipeName: String, type: String) {
        recipeTypeSkipped.getOrPut(modId) { TreeMap() }[recipeName] = type
    }

    fun recordLootRandomSequenceDropped(modId: String, relPath: String) {
        lootRandomSequenceDropped.getOrPut(modId) { TreeSet() }.add(relPath)
    }

    fun recordSoundSubtitleDropped(modId: String, eventName: String) {
        soundSubtitleDropped.getOrPut(modId) { TreeSet() }.add(eventName)
    }

    fun recordVanillaSoundPath(modId: String, javaPath: String, bedrockPath: String) {
        vanillaSoundPaths.getOrPut(modId) { TreeMap() }[javaPath] = bedrockPath
    }

    /** Set of mod ids that have at least one recorded finding. */
    fun modsWithFindings(): Set<String> {
        val ids = TreeSet<String>()
        ids.addAll(recipeCategoryDropped.keys)
        ids.addAll(recipeTypeSkipped.keys)
        ids.addAll(lootRandomSequenceDropped.keys)
        ids.addAll(soundSubtitleDropped.keys)
        ids.addAll(vanillaSoundPaths.keys)
        return ids
    }

    /**
     * Write `<outputRoot>/<modId>/UNTRANSLATABLE.md` for this mod. Always
     * writes — even if there were no findings — so the report's existence is
     * a stable contract per the design spec.
     */
    fun writeFor(modId: String, outputRoot: Path) {
        val report = renderReport(modId)
        val out = outputRoot.resolve("$modId/UNTRANSLATABLE.md")
        out.parent?.createDirectories()
        out.writeText(report)
    }

    /** Public for tests: produce the rendered Markdown for one mod. */
    fun renderReport(modId: String): String {
        val sb = StringBuilder()
        sb.append("# UNTRANSLATABLE — ").append(modId).append('\n')
        sb.append('\n')
        sb.append("Auto-generated by the translator. Lists Java→Bedrock content losses for **")
        sb.append(modId).append("**.\n\n")

        var any = false
        recipeCategoryDropped[modId]?.takeIf { it.isNotEmpty() }?.let { recipes ->
            any = true
            sb.append("## Recipe `category` field dropped\n\n")
            sb.append("Bedrock recipes do not accept Java's datagen-only `category` hint; the field is dropped silently.\n\n")
            for (r in recipes) sb.append("- `").append(r).append("`\n")
            sb.append('\n')
        }
        recipeTypeSkipped[modId]?.takeIf { it.isNotEmpty() }?.let { skipped ->
            any = true
            sb.append("## Recipe types not yet supported\n\n")
            for ((name, type) in skipped) {
                sb.append("- `").append(name).append("`: type `").append(type).append("`\n")
            }
            sb.append('\n')
        }
        lootRandomSequenceDropped[modId]?.takeIf { it.isNotEmpty() }?.let { tables ->
            any = true
            sb.append("## Loot table `random_sequence` dropped\n\n")
            sb.append("Bedrock has no equivalent of Java's `random_sequence` field; loot rolls use the level RNG instead.\n\n")
            for (t in tables) sb.append("- `").append(t).append("`\n")
            sb.append('\n')
        }
        soundSubtitleDropped[modId]?.takeIf { it.isNotEmpty() }?.let { subs ->
            any = true
            sb.append("## Sound `subtitle` dropped\n\n")
            sb.append("Bedrock's subtitle system is structurally different (per-locale text vs. a translation key).\n")
            sb.append("Subtitles for these events were dropped:\n\n")
            for (s in subs) sb.append("- `").append(s).append("`\n")
            sb.append('\n')
        }
        vanillaSoundPaths[modId]?.takeIf { it.isNotEmpty() }?.let { mappings ->
            any = true
            sb.append("## Vanilla sound paths translated approximately\n\n")
            sb.append("Java→Bedrock vanilla-sound path mapping is best-effort for Phase 1a (the translator does not yet ship the full Bedrock sound table). Verify in-game and adjust if a sound is silent or wrong:\n\n")
            for ((java, bedrock) in mappings) {
                sb.append("- `").append(java).append("` → `").append(bedrock).append("`\n")
            }
            sb.append('\n')
        }

        if (!any) {
            sb.append("No translation losses recorded. Everything translated cleanly for this mod.\n")
        }
        return sb.toString()
    }
}
