package com.tweeks.translator.json

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.isRegularFile
import kotlin.io.path.readText
import kotlin.io.path.writeText

/**
 * Translates Java's JSON-keyed `en_us.json` into Bedrock's flat `.lang` text
 * format (`key=Value` lines).
 *
 * Reads:
 *   <mod>/src/generated/clientData/assets/<modid>/lang/en_us.json
 *
 * Writes:
 *   bedrock-out/<modid>/resource_pack/texts/en_US.lang  (uppercase US)
 *   bedrock-out/<modid>/resource_pack/texts/languages.json  (["en_US"])
 *
 * Format notes:
 *   - Bedrock uses `#` as a line-leading comment character. We emit
 *     `## generated by translator` as the first line.
 *   - `#` mid-value is allowed (and we preserve the value verbatim).
 *   - Keys are sorted alphabetically for byte-stable output.
 */
class LangTransform {

    fun translate(modRoot: Path, modId: String, outputRoot: Path) {
        val input = modRoot.resolve("src/generated/clientData/assets/$modId/lang/en_us.json")
        if (!input.isRegularFile()) return

        val outputDir = outputRoot.resolve("$modId/resource_pack/texts")
        outputDir.createDirectories()

        val langContent = renderLang(input.readText())
        outputDir.resolve("en_US.lang").writeText(langContent)

        // languages.json — required for Bedrock to even look at the .lang file.
        outputDir.resolve("languages.json").writeText("[\"en_US\"]\n")
    }

    /**
     * Render the raw Java lang JSON as a Bedrock `.lang` document. Public so
     * tests can compare it without touching the filesystem.
     */
    fun renderLang(javaJson: String): String {
        val parsed = Json.parseToJsonElement(javaJson).jsonObject
        val sorted = parsed.entries
            .map { (k, v) -> k to v.jsonPrimitive.content }
            .sortedBy { it.first }

        val sb = StringBuilder()
        sb.append("## generated by translator\n")
        for ((k, v) in sorted) {
            sb.append(k).append('=').append(v).append('\n')
        }
        return sb.toString()
    }
}
