package com.tweeks.translator.json

import com.tweeks.translator.discover.ModDiscovery
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import java.nio.file.Path
import kotlin.io.path.readText

class LangTransformTest {

    private val repoRoot: Path = ModDiscovery.findRepoRoot(Path.of("").toAbsolutePath())

    /**
     * Lang is a plain text format — comparison is byte-exact, not parsed.
     * The first line is the `## generated by translator` header; everything
     * after is alphabetized `key=value` pairs.
     */
    @Test
    fun `securityguard lang renders as alphabetized lang text`() {
        val transform = LangTransform()
        val javaJson = repoRoot
            .resolve("securityguard/src/generated/clientData/assets/securityguard/lang/en_us.json")
            .readText()
        val expected = readGolden("lang/securityguard_en_US.lang")
        val actual = transform.renderLang(javaJson)
        assertEquals(expected, actual)
    }

    private fun readGolden(name: String): String =
        repoRoot.resolve("translator/src/test/resources/goldens/$name").readText()
}
