package com.tweeks.translator.json

import com.tweeks.translator.discover.ModDiscovery
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.isRegularFile
import kotlin.io.path.readText
import kotlin.io.path.writeText

class LangTransformTest {

    private val repoRoot: Path = ModDiscovery.findRepoRoot(Path.of("").toAbsolutePath())

    /**
     * Lang is a plain text format — comparison is byte-exact, not parsed.
     * The first line is the `## generated by translator` header; everything
     * after is alphabetized `key=value` pairs.
     */
    @Test
    fun `securityguard lang renders as alphabetized lang text`() {
        val transform = LangTransform()
        val javaJson = repoRoot
            .resolve("securityguard/src/generated/clientData/assets/securityguard/lang/en_us.json")
            .readText()
        val expected = readGolden("lang/securityguard_en_US.lang")
        val actual = transform.renderLang(javaJson)
        assertEquals(expected, actual)
    }

    @Test
    fun `falls back to src main resources when generated clientData absent`(@TempDir tmp: Path) {
        // Wildwest-style layout: lang lives in src/main/resources, no generated/clientData.
        val modRoot = tmp.resolve("themod")
        val langDir = modRoot.resolve("src/main/resources/assets/themod/lang")
        langDir.createDirectories()
        langDir.resolve("en_us.json").writeText("""{"item.themod.foo":"Foo"}""")

        val out = tmp.resolve("out")
        LangTransform().translate(modRoot, "themod", out)

        val written = out.resolve("themod/resource_pack/texts/en_US.lang")
        assertTrue(written.isRegularFile(), "Expected en_US.lang at $written")
        assertEquals("## generated by translator\nitem.themod.foo=Foo\n", written.readText())
    }

    @Test
    fun `prefers generated clientData over src main resources when both exist`(@TempDir tmp: Path) {
        val modRoot = tmp.resolve("themod")
        val genDir = modRoot.resolve("src/generated/clientData/assets/themod/lang")
        val mainDir = modRoot.resolve("src/main/resources/assets/themod/lang")
        genDir.createDirectories()
        mainDir.createDirectories()
        genDir.resolve("en_us.json").writeText("""{"k":"from_gen"}""")
        mainDir.resolve("en_us.json").writeText("""{"k":"from_main"}""")

        val out = tmp.resolve("out")
        LangTransform().translate(modRoot, "themod", out)

        val written = out.resolve("themod/resource_pack/texts/en_US.lang").readText()
        assertTrue(written.contains("k=from_gen"), "Expected generated/clientData to win, got: $written")
    }

    private fun readGolden(name: String): String =
        repoRoot.resolve("translator/src/test/resources/goldens/$name").readText()
}
