package com.tweeks.translator.diff

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.copyTo
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.io.path.writeText

/**
 * Phase 5.4 functional check: simulate the CI drift gate flow by hand.
 *
 * 1. Take a snapshot of `bedrock-out/securityguard/manifest.json`.
 * 2. Copy it to a "fresh" temp tree.
 * 3. Mutate the temp file.
 * 4. Run [TreeDiff.diff].
 * 5. Assert it surfaces the modified file with the right relPath.
 *
 * This is the closest unit-level analog of the CI gate without spinning up
 * a full Gradle subprocess.
 */
class DriftDetectionTest {

    @Test
    fun `drift on a single committed file is reported`(@TempDir tmp: Path) {
        val expected = tmp.resolve("expected").also { it.createDirectories() }
        val actual = tmp.resolve("actual").also { it.createDirectories() }

        // Two trees, identical content → no drift.
        val rel = "modA/manifest.json"
        val ePath = expected.resolve(rel).also { it.parent.createDirectories() }
        val aPath = actual.resolve(rel).also { it.parent.createDirectories() }
        ePath.writeText("""{"hello": 1}""")
        aPath.writeText("""{"hello": 1}""")
        assertEquals(0, TreeDiff.diff(expected, actual).size)

        // Mutate the actual file → drift.
        aPath.writeText("""{"hello": 2}""")
        val diff = TreeDiff.diff(expected, actual)
        assertEquals(1, diff.size)
        val mod = diff.single() as TreeDiff.Entry.Modified
        assertEquals(rel, mod.relPath)

        // Summary names the file and tells the user how to fix.
        val summary = TreeDiff.summary(diff)
        assertTrue(summary.contains(rel)) { summary }
        assertTrue(summary.contains("Drift detected")) { summary }
    }

    @Test
    fun `drift on added file is reported`(@TempDir tmp: Path) {
        val expected = tmp.resolve("expected").also { it.createDirectories() }
        val actual = tmp.resolve("actual").also { it.createDirectories() }

        // Add a file to actual (re-translation produced something new).
        val newRel = "modA/new_recipe.json"
        actual.resolve(newRel).also { it.parent.createDirectories() }.writeText("""{"r": 1}""")

        val diff = TreeDiff.diff(expected, actual)
        assertEquals(1, diff.size)
        val added = diff.single() as TreeDiff.Entry.Added
        assertEquals(newRel, added.relPath)
    }

    @Test
    fun `drift on deleted file is reported`(@TempDir tmp: Path) {
        val expected = tmp.resolve("expected").also { it.createDirectories() }
        val actual = tmp.resolve("actual").also { it.createDirectories() }

        // File present in expected, missing in actual (re-translation
        // dropped it — e.g. a recipe was removed from sources).
        val goneRel = "modA/old_recipe.json"
        expected.resolve(goneRel).also { it.parent.createDirectories() }.writeText("""{"r": 1}""")

        val diff = TreeDiff.diff(expected, actual)
        assertEquals(1, diff.size)
        val deleted = diff.single() as TreeDiff.Entry.Deleted
        assertEquals(goneRel, deleted.relPath)
    }

    @Test
    fun `mcaddon zips at root are excluded from drift comparison`(@TempDir tmp: Path) {
        // The committed bedrock-out/ may have *.mcaddon zips left behind
        // from a previous packAddon run. The temp tree generated by --diff
        // never contains them. Without filtering, every CI run would
        // detect spurious "deleted" drift.
        val expected = tmp.resolve("expected").also { it.createDirectories() }
        val actual = tmp.resolve("actual").also { it.createDirectories() }

        expected.resolve("securityguard.mcaddon").writeText("zip-bytes-go-here")
        // Even with no other content, the diff should be empty.
        assertEquals(0, TreeDiff.diff(expected, actual).size)
    }
}
