#!/usr/bin/env python3
"""Generate 16x16 RGBA PNG item icon textures for starwars flat-icon items.

Reuses the chunk/PNG writer approach from wildwest/tools/gen_textures.py,
parametrized to a 16x16 canvas (standard flat item-icon size) instead of the
64x64 humanoid skin layout used for mob textures.

gen_blaster_pistol()/gen_blaster_rifle() below are kept for reference but are
NOT called from __main__ anymore — the blasters moved to full 3D voxel models
with a 32x32 texture atlas generated by gen_weapon_models.py; re-running
those two functions would stomp the (differently-shaped) 32x32 PNGs with a
stale 16x16 flat icon. Everything actually invoked here now is stormtrooper
armor: 16x16 icons — shaped silhouettes (dome/torso/leg/boot outlines, not
flat rects) painted via outline_and_fill() below, with a black outline, 3
white tones (top-left highlight / base / bottom-right shade), and piece-
specific black/gray detailing (T-visor, ab-plate seams, knee seams, sole
line) — matching the paint_stormtrooper palette in gen_textures.py.
"""
import struct, zlib, sys, os

W, H = 16, 16

def rect(rgba, x0, y0, x1, y1, color):
    """Fill (x0..x1, y0..y1) — half-open in x and y — with color."""
    r, g, b, a = color
    for y in range(y0, y1):
        for x in range(x0, x1):
            if x < 0 or x >= W or y < 0 or y >= H:
                continue
            i = 4 * (y * W + x)
            rgba[i + 0] = r
            rgba[i + 1] = g
            rgba[i + 2] = b
            rgba[i + 3] = a

def write_png(path, rgba):
    """Write a WxH RGBA PNG from a flat byte buffer."""
    sig = b'\x89PNG\r\n\x1a\n'
    def chunk(tag, data):
        crc = zlib.crc32(tag + data) & 0xffffffff
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', crc)

    ihdr = struct.pack('>IIBBBBB', W, H, 8, 6, 0, 0, 0)  # 8-bit RGBA
    raw = bytearray()
    for y in range(H):
        raw.append(0)  # filter type 'none' per scanline
        raw.extend(rgba[4*W*y : 4*W*(y+1)])
    idat = zlib.compress(bytes(raw))
    iend = b''
    out = sig + chunk(b'IHDR', ihdr) + chunk(b'IDAT', idat) + chunk(b'IEND', iend)
    with open(path, 'wb') as f:
        f.write(out)

# Palette
GUNMETAL   = (0x2A, 0x2A, 0x30, 0xFF)
HIGHLIGHT  = (0x55, 0x55, 0x60, 0xFF)
GRIP_BLACK = (0x18, 0x18, 0x18, 0xFF)
MUZZLE     = (0x66, 0x30, 0x30, 0xFF)
SCOPE      = (0x80, 0x80, 0x88, 0xFF)
STOCK_WOOD = (0x3A, 0x30, 0x28, 0xFF)
STOCK_DARK = (0x2A, 0x22, 0x1A, 0xFF)
OUTLINE    = (0x0A, 0x0A, 0x0C, 0xFF)

# Stormtrooper armor palette — matches gen_textures.py's paint_stormtrooper.
ARMOR_WHITE    = (0xEE, 0xEE, 0xF2, 0xFF)
ARMOR_WHITE_HI = (0xFF, 0xFF, 0xFF, 0xFF)
ARMOR_WHITE_SH = (0xC8, 0xC8, 0xD2, 0xFF)
ARMOR_BLACK    = (0x16, 0x16, 0x1A, 0xFF)
ARMOR_GRAY     = (0x8A, 0x8A, 0x94, 0xFF)  # aerator dots / sole line — matches
                                            # gen_textures.py's GRAY exactly.


def outline_and_fill(rgba, segs, outline=ARMOR_BLACK, base=ARMOR_WHITE,
                      hi=ARMOR_WHITE_HI, sh=ARMOR_WHITE_SH,
                      hi_rows=(), sh_rows=()):
    """Paint a silhouette from per-row (y, [(x0,x1), ...]) boundary segments
    (half-open x ranges). Each row is outlined 1px black, then filled 1px
    inset with `base` — leaving a black outline ring on every edge (left,
    right, top, bottom, and any stepped corners) without a separate
    outline pass. Rows listed in hi_rows get their left half of fill
    replaced with `hi` (top-left highlight); rows in sh_rows get their
    right half replaced with `sh` (bottom-right shade) — giving the
    required 3+ tone (hi/base/sh) + outline look."""
    for y, ranges in segs:
        for x0, x1 in ranges:
            rect(rgba, x0, y, x1, y + 1, outline)
    for y, ranges in segs:
        for x0, x1 in ranges:
            fx0, fx1 = x0 + 1, x1 - 1
            if fx1 <= fx0:
                continue
            if y in hi_rows:
                mid = fx0 + max(1, (fx1 - fx0) // 2)
                rect(rgba, fx0, y, mid, y + 1, hi)
                rect(rgba, mid, y, fx1, y + 1, base)
            elif y in sh_rows:
                mid = fx0 + max(1, (fx1 - fx0) // 2)
                rect(rgba, fx0, y, mid, y + 1, base)
                rect(rgba, mid, y, fx1, y + 1, sh)
            else:
                rect(rgba, fx0, y, fx1, y + 1, base)

def gen_blaster_pistol(out_path):
    rgba = bytearray(W * H * 4)  # fully transparent

    # Body: barrel + frame running left-to-right across the middle rows.
    rect(rgba, 2, 6, 13, 9, GUNMETAL)
    # Light edge highlight along the top row of the body.
    rect(rgba, 2, 6, 13, 7, HIGHLIGHT)
    # Outline under the body for definition.
    rect(rgba, 2, 9, 13, 10, OUTLINE)

    # Muzzle tip at the front (right) end of the barrel.
    rect(rgba, 12, 6, 14, 9, MUZZLE)
    rect(rgba, 13, 7, 14, 8, HIGHLIGHT)

    # Scope notch — rear sight bump on top of the frame.
    rect(rgba, 4, 4, 6, 6, SCOPE)
    rect(rgba, 4, 5, 6, 6, GUNMETAL)

    # Grip: black, angled downward-right, built from stacked 2px rects.
    rect(rgba, 7, 9, 9, 11, GRIP_BLACK)
    rect(rgba, 8, 11, 10, 13, GRIP_BLACK)
    rect(rgba, 9, 13, 11, 15, GRIP_BLACK)
    # Trigger guard sliver in front of the grip.
    rect(rgba, 6, 9, 7, 11, OUTLINE)

    write_png(out_path, rgba)

def gen_blaster_rifle(out_path):
    rgba = bytearray(W * H * 4)  # fully transparent

    # Long body/barrel spanning most of the 16px width.
    rect(rgba, 1, 6, 15, 8, GUNMETAL)
    rect(rgba, 1, 6, 15, 7, HIGHLIGHT)
    rect(rgba, 1, 8, 15, 9, OUTLINE)

    # Barrel tip at the far right.
    rect(rgba, 14, 6, 16, 8, MUZZLE)

    # Wood-brown stock at the left end, with darker underside shading.
    rect(rgba, 0, 5, 4, 9, STOCK_WOOD)
    rect(rgba, 0, 8, 4, 10, STOCK_DARK)
    rect(rgba, 0, 5, 4, 6, HIGHLIGHT)

    # Folding stock line — thin diagonal seam across the stock.
    rect(rgba, 2, 6, 3, 7, STOCK_DARK)
    rect(rgba, 3, 7, 4, 8, STOCK_DARK)

    # Scope notch on top of the receiver.
    rect(rgba, 8, 3, 11, 5, SCOPE)
    rect(rgba, 8, 4, 11, 5, GUNMETAL)
    rect(rgba, 9, 5, 10, 6, GUNMETAL)

    # Grip: black, angled downward-right, built from stacked 2px rects.
    rect(rgba, 9, 8, 11, 10, GRIP_BLACK)
    rect(rgba, 10, 10, 12, 12, GRIP_BLACK)
    rect(rgba, 11, 12, 13, 14, GRIP_BLACK)

    write_png(out_path, rgba)

def gen_stormtrooper_helmet(out_path):
    """Rounded dome silhouette (stepped corners, transparent margins), a
    black T-visor (eye slits joined to a vertical chin drop), gray aerator
    dots, 3 white tones (top-left highlight / base / bottom-right shade)
    and a black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    segs = [
        (2,  [(5, 11)]),
        (3,  [(4, 12)]),
        (4,  [(3, 13)]),
        (5,  [(2, 14)]),
        (6,  [(2, 14)]),
        (7,  [(2, 14)]),
        (8,  [(2, 14)]),
        (9,  [(2, 14)]),
        (10, [(2, 14)]),
        (11, [(3, 13)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),
    ]
    outline_and_fill(rgba, segs, hi_rows={2, 3, 4}, sh_rows={11, 12, 13})

    # T-visor: horizontal eye slits, joined by a vertical chin drop.
    rect(rgba, 4, 6, 7, 8, ARMOR_BLACK)    # left eye slit
    rect(rgba, 9, 6, 12, 8, ARMOR_BLACK)   # right eye slit
    rect(rgba, 7, 6, 9, 12, ARMOR_BLACK)   # vertical chin drop (joins both slits)

    # Aerator dots, just below the chin drop.
    rect(rgba, 6, 12, 7, 13, ARMOR_GRAY)
    rect(rgba, 9, 12, 10, 13, ARMOR_GRAY)

    write_png(out_path, rgba)

def gen_stormtrooper_chestplate(out_path):
    """Shoulder-notched torso silhouette (not a full-width rect): a raised
    collar separated from split shoulder pads by a notch, merging into a
    full torso plate with a 2-horizontal/1-vertical ab-plate seam. 3 white
    tones + black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    segs = [
        (2,  [(6, 10)]),           # collar
        (3,  [(3, 7), (9, 13)]),   # shoulder pads, split by the collar notch
        (4,  [(3, 13)]),
        (5,  [(3, 13)]),
        (6,  [(3, 13)]),
        (7,  [(3, 13)]),
        (8,  [(3, 13)]),
        (9,  [(3, 13)]),
        (10, [(3, 13)]),
        (11, [(4, 12)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),           # waist taper
    ]
    outline_and_fill(rgba, segs, hi_rows={2, 3, 4}, sh_rows={10, 11, 12, 13})

    # Ab-plate seams: 2 horizontal + 1 vertical.
    rect(rgba, 5, 8, 11, 9, ARMOR_BLACK)    # upper horizontal seam
    rect(rgba, 5, 10, 11, 11, ARMOR_BLACK)  # lower horizontal seam
    rect(rgba, 7, 8, 9, 11, ARMOR_BLACK)    # vertical seam connecting them

    write_png(out_path, rgba)

def gen_stormtrooper_leggings(out_path):
    """Two legs joined at a belt band: knee seam lines and a distinct
    thigh/shin tone split, plus a top-highlighted belt. Black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    belt_segs = [
        (2, [(5, 11)]),
        (3, [(3, 13)]),
    ]
    outline_and_fill(rgba, belt_segs, hi_rows={2, 3})

    thigh_segs = [(y, [(3, 7), (9, 13)]) for y in range(4, 8)]
    outline_and_fill(rgba, thigh_segs, base=ARMOR_WHITE)  # lighter thigh tone

    shin_segs = [(y, [(3, 7), (9, 13)]) for y in range(8, 14)]
    outline_and_fill(rgba, shin_segs, base=ARMOR_WHITE_SH)  # darker shin tone

    # Knee seam line, overlaid at the thigh/shin boundary.
    rect(rgba, 4, 7, 6, 8, ARMOR_BLACK)
    rect(rgba, 10, 7, 12, 8, ARMOR_BLACK)

    write_png(out_path, rgba)

def gen_stormtrooper_boots(out_path):
    """Two boot shapes with a raised (wider) ankle cuff, a boot body, and a
    sole line in darker gray. Black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    cuff_segs = [
        (2, [(1, 8), (9, 16)]),
        (3, [(1, 8), (9, 16)]),
    ]
    outline_and_fill(rgba, cuff_segs, hi_rows={2, 3})

    body_segs = [(y, [(2, 7), (10, 15)]) for y in range(4, 12)]
    outline_and_fill(rgba, body_segs, sh_rows={9, 10, 11})

    sole_segs = [(12, [(2, 7), (10, 15)])]
    outline_and_fill(rgba, sole_segs, base=ARMOR_GRAY)  # sole line, darker gray

    write_png(out_path, rgba)

if __name__ == '__main__':
    out_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
    # blaster_pistol.png / blaster_rifle.png are no longer generated here —
    # see the module docstring; gen_weapon_models.py owns those now.
    gen_stormtrooper_helmet(os.path.join(out_dir, 'stormtrooper_helmet.png'))
    gen_stormtrooper_chestplate(os.path.join(out_dir, 'stormtrooper_chestplate.png'))
    gen_stormtrooper_leggings(os.path.join(out_dir, 'stormtrooper_leggings.png'))
    gen_stormtrooper_boots(os.path.join(out_dir, 'stormtrooper_boots.png'))
    print('OK')
