#!/usr/bin/env python3
"""Generate 16x16 RGBA PNG item icon textures for starwars flat-icon items.

Reuses the chunk/PNG writer approach from wildwest/tools/gen_textures.py,
parametrized to a 16x16 canvas (standard flat item-icon size) instead of the
64x64 humanoid skin layout used for mob textures.

gen_blaster_pistol()/gen_blaster_rifle() below are kept for reference but are
NOT called from __main__ anymore — the blasters moved to full 3D voxel models
with a 32x32 texture atlas generated by gen_weapon_models.py; re-running
those two functions would stomp the (differently-shaped) 32x32 PNGs with a
stale 16x16 flat icon. Everything actually invoked here now is stormtrooper
armor: 16x16 icons — shaped silhouettes (dome/torso/leg/boot outlines, not
flat rects) painted via outline_and_fill() below, with a black outline, 3
white tones (top-left highlight / base / bottom-right shade), and piece-
specific black/gray detailing (T-visor, ab-plate seams, knee seams, sole
line) — matching the paint_stormtrooper palette in gen_textures.py.
"""
import struct, zlib, sys, os

W, H = 16, 16

def rect(rgba, x0, y0, x1, y1, color):
    """Fill (x0..x1, y0..y1) — half-open in x and y — with color."""
    r, g, b, a = color
    for y in range(y0, y1):
        for x in range(x0, x1):
            if x < 0 or x >= W or y < 0 or y >= H:
                continue
            i = 4 * (y * W + x)
            rgba[i + 0] = r
            rgba[i + 1] = g
            rgba[i + 2] = b
            rgba[i + 3] = a

def write_png(path, rgba):
    """Write a WxH RGBA PNG from a flat byte buffer."""
    sig = b'\x89PNG\r\n\x1a\n'
    def chunk(tag, data):
        crc = zlib.crc32(tag + data) & 0xffffffff
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', crc)

    ihdr = struct.pack('>IIBBBBB', W, H, 8, 6, 0, 0, 0)  # 8-bit RGBA
    raw = bytearray()
    for y in range(H):
        raw.append(0)  # filter type 'none' per scanline
        raw.extend(rgba[4*W*y : 4*W*(y+1)])
    idat = zlib.compress(bytes(raw))
    iend = b''
    out = sig + chunk(b'IHDR', ihdr) + chunk(b'IDAT', idat) + chunk(b'IEND', iend)
    with open(path, 'wb') as f:
        f.write(out)

# Palette
GUNMETAL   = (0x2A, 0x2A, 0x30, 0xFF)
HIGHLIGHT  = (0x55, 0x55, 0x60, 0xFF)
GRIP_BLACK = (0x18, 0x18, 0x18, 0xFF)
MUZZLE     = (0x66, 0x30, 0x30, 0xFF)
SCOPE      = (0x80, 0x80, 0x88, 0xFF)
STOCK_WOOD = (0x3A, 0x30, 0x28, 0xFF)
STOCK_DARK = (0x2A, 0x22, 0x1A, 0xFF)
OUTLINE    = (0x0A, 0x0A, 0x0C, 0xFF)

# Stormtrooper armor palette — matches gen_textures.py's paint_stormtrooper.
ARMOR_WHITE    = (0xEE, 0xEE, 0xF2, 0xFF)
ARMOR_WHITE_HI = (0xFF, 0xFF, 0xFF, 0xFF)
ARMOR_WHITE_SH = (0xC8, 0xC8, 0xD2, 0xFF)
ARMOR_BLACK    = (0x16, 0x16, 0x1A, 0xFF)
ARMOR_GRAY     = (0x8A, 0x8A, 0x94, 0xFF)  # aerator dots / sole line — matches
                                            # gen_textures.py's GRAY exactly.


def outline_and_fill(rgba, segs, outline=ARMOR_BLACK, base=ARMOR_WHITE,
                      hi=ARMOR_WHITE_HI, sh=ARMOR_WHITE_SH,
                      hi_rows=(), sh_rows=()):
    """Paint a silhouette from per-row (y, [(x0,x1), ...]) boundary segments
    (half-open x ranges). Each row is outlined 1px black, then filled 1px
    inset with `base` — leaving a black outline ring on every edge (left,
    right, top, bottom, and any stepped corners) without a separate
    outline pass. Rows listed in hi_rows get their left half of fill
    replaced with `hi` (top-left highlight); rows in sh_rows get their
    right half replaced with `sh` (bottom-right shade) — giving the
    required 3+ tone (hi/base/sh) + outline look."""
    for y, ranges in segs:
        for x0, x1 in ranges:
            rect(rgba, x0, y, x1, y + 1, outline)
    for y, ranges in segs:
        for x0, x1 in ranges:
            fx0, fx1 = x0 + 1, x1 - 1
            if fx1 <= fx0:
                continue
            if y in hi_rows:
                mid = fx0 + max(1, (fx1 - fx0) // 2)
                rect(rgba, fx0, y, mid, y + 1, hi)
                rect(rgba, mid, y, fx1, y + 1, base)
            elif y in sh_rows:
                mid = fx0 + max(1, (fx1 - fx0) // 2)
                rect(rgba, fx0, y, mid, y + 1, base)
                rect(rgba, mid, y, fx1, y + 1, sh)
            else:
                rect(rgba, fx0, y, fx1, y + 1, base)

def gen_blaster_pistol(out_path):
    rgba = bytearray(W * H * 4)  # fully transparent

    # Body: barrel + frame running left-to-right across the middle rows.
    rect(rgba, 2, 6, 13, 9, GUNMETAL)
    # Light edge highlight along the top row of the body.
    rect(rgba, 2, 6, 13, 7, HIGHLIGHT)
    # Outline under the body for definition.
    rect(rgba, 2, 9, 13, 10, OUTLINE)

    # Muzzle tip at the front (right) end of the barrel.
    rect(rgba, 12, 6, 14, 9, MUZZLE)
    rect(rgba, 13, 7, 14, 8, HIGHLIGHT)

    # Scope notch — rear sight bump on top of the frame.
    rect(rgba, 4, 4, 6, 6, SCOPE)
    rect(rgba, 4, 5, 6, 6, GUNMETAL)

    # Grip: black, angled downward-right, built from stacked 2px rects.
    rect(rgba, 7, 9, 9, 11, GRIP_BLACK)
    rect(rgba, 8, 11, 10, 13, GRIP_BLACK)
    rect(rgba, 9, 13, 11, 15, GRIP_BLACK)
    # Trigger guard sliver in front of the grip.
    rect(rgba, 6, 9, 7, 11, OUTLINE)

    write_png(out_path, rgba)

def gen_blaster_rifle(out_path):
    rgba = bytearray(W * H * 4)  # fully transparent

    # Long body/barrel spanning most of the 16px width.
    rect(rgba, 1, 6, 15, 8, GUNMETAL)
    rect(rgba, 1, 6, 15, 7, HIGHLIGHT)
    rect(rgba, 1, 8, 15, 9, OUTLINE)

    # Barrel tip at the far right.
    rect(rgba, 14, 6, 16, 8, MUZZLE)

    # Wood-brown stock at the left end, with darker underside shading.
    rect(rgba, 0, 5, 4, 9, STOCK_WOOD)
    rect(rgba, 0, 8, 4, 10, STOCK_DARK)
    rect(rgba, 0, 5, 4, 6, HIGHLIGHT)

    # Folding stock line — thin diagonal seam across the stock.
    rect(rgba, 2, 6, 3, 7, STOCK_DARK)
    rect(rgba, 3, 7, 4, 8, STOCK_DARK)

    # Scope notch on top of the receiver.
    rect(rgba, 8, 3, 11, 5, SCOPE)
    rect(rgba, 8, 4, 11, 5, GUNMETAL)
    rect(rgba, 9, 5, 10, 6, GUNMETAL)

    # Grip: black, angled downward-right, built from stacked 2px rects.
    rect(rgba, 9, 8, 11, 10, GRIP_BLACK)
    rect(rgba, 10, 10, 12, 12, GRIP_BLACK)
    rect(rgba, 11, 12, 13, 14, GRIP_BLACK)

    write_png(out_path, rgba)

def gen_stormtrooper_helmet(out_path):
    """Rounded dome silhouette (stepped corners, transparent margins), a
    black T-visor (eye slits joined to a vertical chin drop), gray aerator
    dots, 3 white tones (top-left highlight / base / bottom-right shade)
    and a black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    segs = [
        (2,  [(5, 11)]),
        (3,  [(4, 12)]),
        (4,  [(3, 13)]),
        (5,  [(2, 14)]),
        (6,  [(2, 14)]),
        (7,  [(2, 14)]),
        (8,  [(2, 14)]),
        (9,  [(2, 14)]),
        (10, [(2, 14)]),
        (11, [(3, 13)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),
    ]
    outline_and_fill(rgba, segs, hi_rows={2, 3, 4}, sh_rows={11, 12, 13})

    # T-visor: horizontal eye slits, joined by a vertical chin drop.
    rect(rgba, 4, 6, 7, 8, ARMOR_BLACK)    # left eye slit
    rect(rgba, 9, 6, 12, 8, ARMOR_BLACK)   # right eye slit
    rect(rgba, 7, 6, 9, 12, ARMOR_BLACK)   # vertical chin drop (joins both slits)

    # Aerator dots, just below the chin drop.
    rect(rgba, 6, 12, 7, 13, ARMOR_GRAY)
    rect(rgba, 9, 12, 10, 13, ARMOR_GRAY)

    write_png(out_path, rgba)

def gen_stormtrooper_chestplate(out_path):
    """Shoulder-notched torso silhouette (not a full-width rect): a raised
    collar separated from split shoulder pads by a notch, merging into a
    full torso plate with a 2-horizontal/1-vertical ab-plate seam. 3 white
    tones + black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    segs = [
        (2,  [(6, 10)]),           # collar
        (3,  [(3, 7), (9, 13)]),   # shoulder pads, split by the collar notch
        (4,  [(3, 13)]),
        (5,  [(3, 13)]),
        (6,  [(3, 13)]),
        (7,  [(3, 13)]),
        (8,  [(3, 13)]),
        (9,  [(3, 13)]),
        (10, [(3, 13)]),
        (11, [(4, 12)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),           # waist taper
    ]
    outline_and_fill(rgba, segs, hi_rows={2, 3, 4}, sh_rows={10, 11, 12, 13})

    # Ab-plate seams: 2 horizontal + 1 vertical.
    rect(rgba, 5, 8, 11, 9, ARMOR_BLACK)    # upper horizontal seam
    rect(rgba, 5, 10, 11, 11, ARMOR_BLACK)  # lower horizontal seam
    rect(rgba, 7, 8, 9, 11, ARMOR_BLACK)    # vertical seam connecting them

    write_png(out_path, rgba)

def gen_stormtrooper_leggings(out_path):
    """Two legs joined at a belt band: knee seam lines and a distinct
    thigh/shin tone split, plus a top-highlighted belt. Black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    belt_segs = [
        (2, [(5, 11)]),
        (3, [(3, 13)]),
    ]
    outline_and_fill(rgba, belt_segs, hi_rows={2, 3})

    thigh_segs = [(y, [(3, 7), (9, 13)]) for y in range(4, 8)]
    outline_and_fill(rgba, thigh_segs, base=ARMOR_WHITE)  # lighter thigh tone

    shin_segs = [(y, [(3, 7), (9, 13)]) for y in range(8, 14)]
    outline_and_fill(rgba, shin_segs, base=ARMOR_WHITE_SH)  # darker shin tone

    # Knee seam line, overlaid at the thigh/shin boundary.
    rect(rgba, 4, 7, 6, 8, ARMOR_BLACK)
    rect(rgba, 10, 7, 12, 8, ARMOR_BLACK)

    write_png(out_path, rgba)

def gen_stormtrooper_boots(out_path):
    """Two boot shapes with a raised (wider) ankle cuff, a boot body, and a
    sole line in darker gray. Black outline."""
    rgba = bytearray(W * H * 4)  # fully transparent

    cuff_segs = [
        (2, [(1, 8), (9, 16)]),
        (3, [(1, 8), (9, 16)]),
    ]
    outline_and_fill(rgba, cuff_segs, hi_rows={2, 3})

    body_segs = [(y, [(2, 7), (10, 15)]) for y in range(4, 12)]
    outline_and_fill(rgba, body_segs, sh_rows={9, 10, 11})

    sole_segs = [(12, [(2, 7), (10, 15)])]
    outline_and_fill(rgba, sole_segs, base=ARMOR_GRAY)  # sole line, darker gray

    write_png(out_path, rgba)

# Han Solo armor palette — matches gen_textures.py's paint_han_solo_armor_layers.
HAN_CAP        = (0x4A, 0x35, 0x22, 0xFF)
HAN_CAP_HI     = (0x64, 0x4A, 0x32, 0xFF)
HAN_CAP_DK     = (0x33, 0x24, 0x16, 0xFF)
HAN_SHIRT      = (0xE8, 0xE0, 0xD0, 0xFF)
HAN_VEST       = (0x2B, 0x2B, 0x2B, 0xFF)
HAN_VEST_HI    = (0x45, 0x45, 0x48, 0xFF)
HAN_VEST_DK    = (0x17, 0x17, 0x19, 0xFF)
HAN_TROUSER    = (0x2E, 0x3A, 0x52, 0xFF)
HAN_TROUSER_DK = (0x1F, 0x28, 0x3A, 0xFF)
HAN_STRIPE     = (0xB0, 0x30, 0x30, 0xFF)
HAN_BELT       = (0x5A, 0x40, 0x28, 0xFF)
HAN_BOOT       = (0x54, 0x3A, 0x24, 0xFF)
HAN_BOOT_HI    = (0x6E, 0x50, 0x34, 0xFF)
HAN_BOOT_DK    = (0x3A, 0x28, 0x18, 0xFF)


def gen_han_solo_helmet(out_path):
    """Cap silhouette (same dome shape as the stormtrooper helmet icon,
    minus the T-visor cutout — Han's cap doesn't cover the face) with a
    3-tone brown gradient and a darker brim band across the front."""
    rgba = bytearray(W * H * 4)  # fully transparent

    segs = [
        (2,  [(5, 11)]),
        (3,  [(4, 12)]),
        (4,  [(3, 13)]),
        (5,  [(2, 14)]),
        (6,  [(2, 14)]),
        (7,  [(2, 14)]),
        (8,  [(2, 14)]),
        (9,  [(2, 14)]),
        (10, [(2, 14)]),
        (11, [(3, 13)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),
    ]
    outline_and_fill(rgba, segs, base=HAN_CAP, hi=HAN_CAP_HI, sh=HAN_CAP_DK,
                      hi_rows={2, 3, 4}, sh_rows={11, 12, 13})

    # Brim band across the front of the cap.
    rect(rgba, 3, 9, 13, 10, HAN_CAP_DK)

    write_png(out_path, rgba)

def gen_han_solo_chestplate(out_path):
    """Vest silhouette (same shoulder-notched torso shape as the
    stormtrooper chestplate icon) in black over an off-white open-front
    shirt column down the middle."""
    rgba = bytearray(W * H * 4)  # fully transparent

    segs = [
        (2,  [(6, 10)]),           # collar
        (3,  [(3, 7), (9, 13)]),   # shoulder pads, split by the collar notch
        (4,  [(3, 13)]),
        (5,  [(3, 13)]),
        (6,  [(3, 13)]),
        (7,  [(3, 13)]),
        (8,  [(3, 13)]),
        (9,  [(3, 13)]),
        (10, [(3, 13)]),
        (11, [(4, 12)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),           # waist taper
    ]
    outline_and_fill(rgba, segs, base=HAN_VEST, hi=HAN_VEST_HI, sh=HAN_VEST_DK,
                      hi_rows={2, 3, 4}, sh_rows={10, 11, 12, 13})

    # Open-front shirt column, painted over the vest fill.
    rect(rgba, 7, 5, 9, 12, HAN_SHIRT)

    write_png(out_path, rgba)

def gen_han_solo_leggings(out_path):
    """Two legs joined at a belt band, navy trousers with a red Corellian
    bloodstripe column running down the outer seam of each leg."""
    rgba = bytearray(W * H * 4)  # fully transparent

    belt_segs = [
        (2, [(5, 11)]),
        (3, [(3, 13)]),
    ]
    outline_and_fill(rgba, belt_segs, base=HAN_BELT)

    leg_segs = [(y, [(3, 7), (9, 13)]) for y in range(4, 14)]
    outline_and_fill(rgba, leg_segs, base=HAN_TROUSER, sh=HAN_TROUSER_DK,
                      sh_rows=set(range(9, 14)))

    # Bloodstripe columns, one per leg.
    rect(rgba, 4, 4, 5, 14, HAN_STRIPE)
    rect(rgba, 11, 4, 12, 14, HAN_STRIPE)

    write_png(out_path, rgba)

def gen_han_solo_boots(out_path):
    """Two boot shapes (same silhouette as the stormtrooper boots icon), a
    3-tone brown gradient with a darker sole line."""
    rgba = bytearray(W * H * 4)  # fully transparent

    cuff_segs = [
        (2, [(1, 8), (9, 16)]),
        (3, [(1, 8), (9, 16)]),
    ]
    outline_and_fill(rgba, cuff_segs, base=HAN_BOOT, hi=HAN_BOOT_HI,
                      hi_rows={2, 3})

    body_segs = [(y, [(2, 7), (10, 15)]) for y in range(4, 12)]
    outline_and_fill(rgba, body_segs, base=HAN_BOOT, sh=HAN_BOOT_DK,
                      sh_rows={9, 10, 11})

    sole_segs = [(12, [(2, 7), (10, 15)])]
    outline_and_fill(rgba, sole_segs, base=HAN_BOOT_DK)  # sole line, darkest brown

    write_png(out_path, rgba)

def gen_landspeeder(out_path):
    """16x16 side-profile of the X-34 landspeeder (spec §5.6): a sand-orange
    hull wedge (rows 7-10) with nose tip at the left, an open two-seat
    cockpit notch cut into the deck with an angled windshield slab at the
    leading edge, and three gunmetal turbine pods stacked at the rear
    (right side) each with a dark center. Uses the same SPEEDER_* palette
    values as gen_textures.py's paint_landspeeder (redeclared locally per
    this file's existing per-item convention — see module docstring)."""
    rgba = bytearray(W * H * 4)  # fully transparent

    body     = (0xC8, 0x86, 0x4A, 0xFF)
    body_hi  = (0xE0, 0xA6, 0x6A, 0xFF)
    body_dk  = (0x9A, 0x64, 0x36, 0xFF)
    rust     = (0x7A, 0x52, 0x30, 0xFF)
    cockpit  = (0x2A, 0x2A, 0x30, 0xFF)
    glass    = (0xA8, 0xC8, 0xD8, 0xFF)
    glass_hi = (0xD0, 0xE8, 0xF0, 0xFF)
    metal    = (0x8A, 0x8A, 0x92, 0xFF)
    metal_dk = (0x5A, 0x5A, 0x62, 0xFF)
    metal_hi = (0xB4, 0xB4, 0xBC, 0xFF)

    # Hull wedge, rows 7-10: sand-orange body, top highlight row, underside
    # shade row, nose tip poking to the left edge, 2 rust weathering flecks.
    rect(rgba, 2, 7, 14, 8, body_hi)    # top highlight row
    rect(rgba, 1, 8, 14, 10, body)      # main hull body (nose tip at x=1)
    rect(rgba, 2, 10, 14, 11, body_dk)  # underside shade row
    rect(rgba, 5, 8, 6, 9, rust)
    rect(rgba, 10, 9, 11, 10, rust)

    # Open two-seat cockpit notch cut into the hull deck (rows 5-7), with an
    # angled windshield slab (2-tone glass) at the leading (left) edge.
    rect(rgba, 5, 5, 10, 8, cockpit)
    rect(rgba, 5, 5, 7, 7, glass)
    rect(rgba, 5, 5, 6, 6, glass_hi)

    # Three rear turbine pods (right side), gunmetal w/ a top-rim highlight
    # and a dark center intake each — stacked to read as circles in profile.
    for cy in (6, 9, 12):
        rect(rgba, 12, cy - 1, 15, cy + 2, metal)
        rect(rgba, 12, cy - 1, 15, cy, metal_hi)
        rect(rgba, 13, cy, 14, cy + 1, metal_dk)

    write_png(out_path, rgba)

def gen_star_compass(out_path):
    """16x16 star-compass icon for the hyperspace-portal feature: a round
    brass/gold compass body (stepped-circle silhouette via outline_and_fill,
    rim highlight top-left / shade bottom-right per the existing icon style),
    a dark navy star-field face with 4 tiny white star pixels, a 4-point
    white needle with light-blue tips centered on the face, and a small red
    north pixel above the needle."""
    rgba = bytearray(W * H * 4)  # fully transparent

    brass    = (0xC8, 0x9A, 0x46, 0xFF)
    brass_hi = (0xE8, 0xC8, 0x74, 0xFF)
    brass_sh = (0x8E, 0x66, 0x2C, 0xFF)
    brass_ol = (0x2E, 0x20, 0x0E, 0xFF)   # deep-brown outline
    navy     = (0x14, 0x1C, 0x34, 0xFF)   # star-field face
    navy_dk  = (0x0C, 0x12, 0x24, 0xFF)   # face shade, lower rows
    star     = (0xF0, 0xF4, 0xFF, 0xFF)
    needle   = (0xF6, 0xF9, 0xFF, 0xFF)
    needle_b = (0x9C, 0xC4, 0xF0, 0xFF)   # light-blue needle tips
    north    = (0xC0, 0x30, 0x28, 0xFF)

    # Round body: stepped-circle silhouette, 3 brass tones + outline.
    segs = [
        (2,  [(5, 11)]),
        (3,  [(4, 12)]),
        (4,  [(3, 13)]),
        (5,  [(2, 14)]),
        (6,  [(2, 14)]),
        (7,  [(2, 14)]),
        (8,  [(2, 14)]),
        (9,  [(2, 14)]),
        (10, [(2, 14)]),
        (11, [(3, 13)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),
    ]
    outline_and_fill(rgba, segs, outline=brass_ol, base=brass, hi=brass_hi,
                      sh=brass_sh, hi_rows={2, 3, 4}, sh_rows={11, 12, 13})

    # Face: inset navy disc (leaves a 1-2px brass ring inside the outline),
    # shaded darker on the bottom rows.
    rect(rgba, 6, 4, 10, 5, navy)
    rect(rgba, 5, 5, 11, 6, navy)
    rect(rgba, 4, 6, 12, 10, navy)
    rect(rgba, 5, 10, 11, 11, navy_dk)
    rect(rgba, 6, 11, 10, 12, navy_dk)

    # Tiny background stars on the face, clear of the needle arms.
    rect(rgba, 5, 5, 6, 6, star)
    rect(rgba, 11, 6, 12, 7, star)
    rect(rgba, 4, 9, 5, 10, star)
    rect(rgba, 9, 11, 10, 12, star)

    # 4-point star needle: white cross arms with light-blue tips.
    rect(rgba, 7, 5, 9, 11, needle)     # N-S arm
    rect(rgba, 5, 7, 11, 9, needle)     # E-W arm
    rect(rgba, 7, 5, 9, 6, needle_b)    # north tip
    rect(rgba, 7, 10, 9, 11, needle_b)  # south tip
    rect(rgba, 5, 7, 6, 9, needle_b)    # west tip
    rect(rgba, 10, 7, 11, 9, needle_b)  # east tip

    # Red north marker, just above the needle's north tip.
    rect(rgba, 7, 4, 8, 5, north)

    write_png(out_path, rgba)


def gen_cantina_record(out_path):
    """16x16 music-disc icon for the cantina tune: near-black vinyl disc
    (stepped circle, 3 tones + groove ring), warm amber label with a dark
    spindle hole, one specular highlight arc top-left."""
    rgba = bytearray(W * H * 4)

    vinyl    = (0x24, 0x24, 0x28, 0xFF)
    vinyl_hi = (0x3E, 0x3E, 0x46, 0xFF)
    vinyl_sh = (0x16, 0x16, 0x1A, 0xFF)
    vinyl_ol = (0x0A, 0x0A, 0x0C, 0xFF)
    groove   = (0x30, 0x30, 0x36, 0xFF)
    label    = (0xE8, 0xA3, 0x3D, 0xFF)   # cantina amber
    label_sh = (0xB8, 0x7A, 0x24, 0xFF)
    hole     = (0x0A, 0x0A, 0x0C, 0xFF)
    shine    = (0x8A, 0x8A, 0x96, 0xFF)

    segs = [
        (2,  [(5, 11)]),
        (3,  [(4, 12)]),
        (4,  [(3, 13)]),
        (5,  [(2, 14)]),
        (6,  [(2, 14)]),
        (7,  [(2, 14)]),
        (8,  [(2, 14)]),
        (9,  [(2, 14)]),
        (10, [(2, 14)]),
        (11, [(3, 13)]),
        (12, [(4, 12)]),
        (13, [(5, 11)]),
    ]
    outline_and_fill(rgba, segs, outline=vinyl_ol, base=vinyl, hi=vinyl_hi,
                      sh=vinyl_sh, hi_rows={2, 3, 4}, sh_rows={11, 12, 13})

    # Groove ring between rim and label.
    rect(rgba, 5, 4, 11, 5, groove)
    rect(rgba, 4, 5, 5, 11, groove)
    rect(rgba, 11, 5, 12, 11, groove)
    rect(rgba, 5, 11, 11, 12, groove)

    # Amber label with shaded lower half and spindle hole.
    rect(rgba, 6, 6, 10, 8, label)
    rect(rgba, 6, 8, 10, 10, label_sh)
    rect(rgba, 7, 7, 9, 9, hole)

    # Specular arc top-left on the vinyl.
    rect(rgba, 4, 3, 6, 4, shine)
    rect(rgba, 3, 4, 4, 6, shine)

    write_png(out_path, rgba)


def gen_galaxy_map(out_path):
    """16x16 galaxy-map icon: a dark holo-tablet with a gold frame, a spray
    of star pixels, an orbit arc, and one amber 'you are here' planet dot."""
    rgba = bytearray(W * H * 4)

    frame    = (0xC8, 0x9A, 0x46, 0xFF)   # gold frame
    frame_sh = (0x8E, 0x66, 0x2C, 0xFF)
    slate    = (0x10, 0x16, 0x2A, 0xFF)   # deep space screen
    slate_hi = (0x1A, 0x22, 0x40, 0xFF)
    star     = (0xE8, 0xEE, 0xFF, 0xFF)
    star_dim = (0x8C, 0x9A, 0xC0, 0xFF)
    orbit    = (0x3C, 0x50, 0x84, 0xFF)
    here     = (0xE8, 0xA3, 0x3D, 0xFF)   # amber planet marker

    # Gold frame with shaded bottom/right, screen inset.
    rect(rgba, 1, 1, 15, 15, frame)
    rect(rgba, 13, 2, 15, 15, frame_sh)
    rect(rgba, 2, 13, 15, 15, frame_sh)
    rect(rgba, 3, 3, 13, 13, slate)
    rect(rgba, 3, 3, 13, 6, slate_hi)

    # Orbit arc sweeping the screen.
    for x, y in ((4, 10), (5, 9), (6, 8), (7, 8), (8, 7), (9, 7), (10, 6), (11, 5)):
        rect(rgba, x, y, x + 1, y + 1, orbit)

    # Stars, mixed brightness.
    for x, y, c in ((5, 4, star), (10, 4, star_dim), (12, 8, star),
                    (4, 6, star_dim), (8, 11, star), (11, 11, star_dim)):
        rect(rgba, x, y, x + 1, y + 1, c)

    # 'You are here' planet dot with a tiny shadow.
    rect(rgba, 6, 6, 8, 8, here)
    rect(rgba, 7, 7, 8, 8, (0xB8, 0x7A, 0x24, 0xFF))

    write_png(out_path, rgba)

# ── Kyber crystals + saber hilt ────────────────────────────────────────
# Lightsaber-crafting item icons. gen_kyber_crystal paints a faceted gem
# shard (angular silhouette, diagonal lit->shadow facet gradient, dark
# facet-edge ring, glowing core, one white sparkle) in any hue; the 'red'
# (bled/Sith) variant gets a jaggier outline plus darker veins.
# gen_saber_hilt paints a bladeless chrome cylinder hilt. Both are static
# and fully explicit — no randomness — so re-runs are byte-identical.

def _mix(c0, c1, f):
    """Blend RGB c0 toward c1 by fraction f (per channel, rounded)."""
    return tuple(int(a + (b - a) * f + 0.5) for a, b in zip(c0, c1))

def _rgba(rgb, a=0xFF):
    """RGB triple -> RGBA 4-tuple (opaque by default)."""
    return (rgb[0], rgb[1], rgb[2], a)


def gen_kyber_crystal(color_rgb, variant, out_path):
    """16x16 faceted kyber shard for `color_rgb`. `variant` names the hue
    ('blue'/'green'/'red'/'purple'); 'red' also triggers the jagged Sith
    silhouette + dark veins."""
    rgba = bytearray(W * H * 4)  # fully transparent

    c_edge   = _rgba(_mix(color_rgb, (0, 0, 0), 0.58))          # facet edges
    c_dark   = _rgba(_mix(color_rgb, (0, 0, 0), 0.30))          # shadow facet
    c_mid    = _rgba(color_rgb)                                 # body
    c_bright = _rgba(_mix(color_rgb, (255, 255, 255), 0.40))    # lit facet
    c_core   = _rgba(_mix(color_rgb, (255, 255, 255), 0.66))    # glowing core
    c_vein   = _rgba(_mix(color_rgb, (0, 0, 0), 0.66))          # Sith veins
    sparkle  = (0xFF, 0xFF, 0xFF, 0xFF)

    def px(x, y, color):
        rect(rgba, x, y, x + 1, y + 1, color)

    # Angular shard silhouette (half-open x-span per row), symmetric about
    # x=7.5: a short crown above a longer pavilion tapering to a point.
    spans = {
        2: (7, 9), 3: (6, 10), 4: (5, 11), 5: (4, 12), 6: (4, 12),
        7: (5, 11), 8: (5, 11), 9: (6, 10), 10: (6, 10), 11: (7, 9), 12: (7, 9),
    }
    jagged = variant == 'red'
    if jagged:
        spans = dict(spans)
        spans[1] = (7, 9)     # spike above the crown
        spans[7] = (4, 11)    # left-jut facet
        spans[9] = (6, 11)    # right-jut facet
        spans[13] = (7, 8)    # long sharp bottom spike

    # 1) Facet gradient fill: lit crown-left, mid crown-right & pavilion-left,
    #    shadowed pavilion-right — a diagonal light-to-dark cut.
    for y, (x0, x1) in spans.items():
        for x in range(x0, x1):
            crown = y <= 6
            left = x <= 7
            if crown and left:
                col = c_bright
            elif crown or left:
                col = c_mid
            else:
                col = c_dark
            px(x, y, col)

    # 2) Facet-edge ring: darken each row's left/right border + top/bottom caps.
    for y, (x0, x1) in spans.items():
        px(x0, y, c_edge)
        px(x1 - 1, y, c_edge)
    for x in range(*spans[min(spans)]):
        px(x, min(spans), c_edge)
    for x in range(*spans[max(spans)]):
        px(x, max(spans), c_edge)

    # 3) Glowing core: a near-white-tinted cluster just above center.
    px(7, 4, c_bright); px(8, 4, c_bright)
    px(7, 5, c_core);   px(8, 5, c_core)
    px(7, 6, c_core);   px(8, 6, c_core)

    # 4) Red veins: two dark diagonal fractures across the body.
    if jagged:
        for vx, vy in ((6, 4), (7, 6), (8, 8), (9, 10)):
            px(vx, vy, c_vein)
        for vx, vy in ((9, 5), (8, 7), (7, 9)):
            px(vx, vy, c_vein)

    # 5) One white sparkle on the upper-left lit facet.
    px(6, 4, sparkle)

    write_png(out_path, rgba)


def gen_saber_hilt(out_path):
    """16x16 lightsaber hilt icon (no blade): a vertical chrome cylinder —
    4 metal tones (edge/highlight/base/shade columns for a rounded read), a
    flared emitter head with a dark blade aperture at the top, three black
    grip bands and a red activation stud."""
    rgba = bytearray(W * H * 4)  # fully transparent

    edge    = (0x34, 0x37, 0x3E, 0xFF)   # dark metal outline
    hi      = (0xD6, 0xDA, 0xE2, 0xFF)   # left specular highlight
    base    = (0x9C, 0xA0, 0xA8, 0xFF)   # chrome base
    shade   = (0x64, 0x68, 0x70, 0xFF)   # right shade
    emit    = (0xE4, 0xE8, 0xF0, 0xFF)   # emitter lip (brightest metal)
    hole    = (0x1C, 0x1E, 0x26, 0xFF)   # blade aperture (dark)
    band    = (0x17, 0x17, 0x1B, 0xFF)   # black grip band
    band_hi = (0x30, 0x30, 0x38, 0xFF)   # band sheen
    stud    = (0xC4, 0x30, 0x28, 0xFF)   # red activation button
    stud_hi = (0xE8, 0x60, 0x50, 0xFF)

    def px(x, y, c):
        rect(rgba, x, y, x + 1, y + 1, c)

    def metal_row(y, x0, x1):
        """A horizontal metal slice: edge | highlight | base... | shade | edge."""
        for x in range(x0, x1):
            if x == x0 or x == x1 - 1:
                c = edge
            elif x == x0 + 1:
                c = hi
            elif x == x1 - 2:
                c = shade
            else:
                c = base
            px(x, y, c)

    # Flared emitter head, rows 1-2, with a dark blade aperture dead center.
    metal_row(1, 4, 12)
    metal_row(2, 4, 12)
    for x in range(5, 11):
        px(x, 1, emit)            # bright emitter lip
    px(4, 1, edge); px(11, 1, edge)
    px(7, 1, hole); px(8, 1, hole)

    # Neck taper, then the body cylinder (6px wide) rows 3-13.
    metal_row(3, 5, 11)
    for y in range(4, 14):
        metal_row(y, 5, 11)

    # Pommel cap, row 14 (darker).
    for x in range(5, 11):
        px(x, 14, edge if x in (5, 10) else shade)

    # Three black grip bands wrapping the body interior.
    for by in (7, 9, 11):
        for x in range(6, 10):
            px(x, by, band)
        px(6, by, band_hi)

    # Red activation stud on the upper body.
    px(8, 5, stud); px(9, 5, stud)
    px(8, 5, stud_hi)

    write_png(out_path, rgba)


if __name__ == '__main__':
    out_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
    # blaster_pistol.png / blaster_rifle.png are no longer generated here —
    # see the module docstring; gen_weapon_models.py owns those now.
    gen_stormtrooper_helmet(os.path.join(out_dir, 'stormtrooper_helmet.png'))
    gen_stormtrooper_chestplate(os.path.join(out_dir, 'stormtrooper_chestplate.png'))
    gen_stormtrooper_leggings(os.path.join(out_dir, 'stormtrooper_leggings.png'))
    gen_stormtrooper_boots(os.path.join(out_dir, 'stormtrooper_boots.png'))
    gen_han_solo_helmet(os.path.join(out_dir, 'han_solo_helmet.png'))
    gen_han_solo_chestplate(os.path.join(out_dir, 'han_solo_chestplate.png'))
    gen_han_solo_leggings(os.path.join(out_dir, 'han_solo_leggings.png'))
    gen_han_solo_boots(os.path.join(out_dir, 'han_solo_boots.png'))
    gen_landspeeder(os.path.join(out_dir, 'landspeeder.png'))
    gen_star_compass(os.path.join(out_dir, 'star_compass.png'))
    gen_cantina_record(os.path.join(out_dir, 'cantina_record.png'))
    gen_galaxy_map(os.path.join(out_dir, 'galaxy_map.png'))
    # Kyber crystals (one icon per hue) + the bladeless saber hilt.
    for variant, color in (('blue',   (0x3E, 0x7B, 0xFF)),
                           ('green',  (0x3B, 0xE8, 0x6B)),
                           ('red',    (0xFF, 0x2A, 0x2A)),
                           ('purple', (0xA6, 0x3B, 0xE8))):
        gen_kyber_crystal(color, variant, os.path.join(out_dir, f'kyber_crystal_{variant}.png'))
    gen_saber_hilt(os.path.join(out_dir, 'saber_hilt.png'))
    print('OK')
